// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByyCHj-fCJxdRBJg6jjUluS34itjE6obQ',
    appId: '1:471764593183:web:ed37d9964318da31c0c32a',
    messagingSenderId: '471764593183',
    projectId: 'breakout-revival-402311',
    authDomain: 'breakout-revival-402311.firebaseapp.com',
    storageBucket: 'breakout-revival-402311.appspot.com',
    measurementId: 'G-LVCFXNYNX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxEYvndc1jSq3_UPyrmgruu_Tl5MQ6NeA',
    appId: '1:471764593183:android:ac2b8be771e836d4c0c32a',
    messagingSenderId: '471764593183',
    projectId: 'breakout-revival-402311',
    storageBucket: 'breakout-revival-402311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_xITNm4G2ZyXn6CvqnPpnjI7s-QkyI4',
    appId: '1:471764593183:ios:026efcb8bceaf910c0c32a',
    messagingSenderId: '471764593183',
    projectId: 'breakout-revival-402311',
    storageBucket: 'breakout-revival-402311.appspot.com',
    androidClientId: '471764593183-2dtbt71jscuoc172jp9nb2dio8vv071n.apps.googleusercontent.com',
    iosClientId: '471764593183-i2736ngsube0831dihhn83p6tp12je8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.breakoutRevival',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_xITNm4G2ZyXn6CvqnPpnjI7s-QkyI4',
    appId: '1:471764593183:ios:8744075cfbd1d420c0c32a',
    messagingSenderId: '471764593183',
    projectId: 'breakout-revival-402311',
    storageBucket: 'breakout-revival-402311.appspot.com',
    androidClientId: '471764593183-2dtbt71jscuoc172jp9nb2dio8vv071n.apps.googleusercontent.com',
    iosClientId: '471764593183-la3gsftukdojb27c344uvf3mi694okii.apps.googleusercontent.com',
    iosBundleId: 'com.example.breakoutRevival.RunnerTests',
  );
}
